### ISSUE TITLE
cannot compile after cloning

### ISSUE THREAD

**Issue by LeiYangGH** [WELL-E/LoginSample#3]
I have .net 4.5 and vs2019, after cloning I compile entire project but failed.
Did you forget add referencing binaries/nuget package references to the project?
![image](https://user-images.githubusercontent.com/5386998/80048093-c7d1b800-8541-11ea-9e5d-eb1ca190ecd8.png)

**Comment by WELL-E** [comment]
Install Expression Blend then reference System.Windows.Interactivity.dll or add System.Windows.Interactivity.WPF nuget package
